name: 二十二夜的雪
permalink: :year/:month/:day/:title
baseurl: /cassidyblog
imgurl: /cassidyblog

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2023
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : tiantao5@gmail.com
  github : Snownight22
  weibo : https://weibo.com/u/1516249411
  weixin : https://mp.weixin.qq.com/s/zOmCbSw5DADT3-7l5yEt2Q
  link : https://snownight22.github.io/TTworksBlog/

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/archive"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed
