# Site settings
name: 二十二夜的雪
email: tiantao714@163.com
author: Snownight22
url: https://snownight22.github.io/cassidyBlog/
resume_site: https://snownight22.github.io/cassidyBlog/
github: https://github.com/Snownight22/
baseurl: "/cassidyBlog"
description: Snownight22的博客
meta_description: Snownight22;个人博客;非淡泊无以明志;非宁静无以致远
motto: 非淡泊无以明志;非宁静无以致远.
banner: 非淡泊无以明志;非宁静无以致远。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" #类型是posts的文件
    values:
      layout: "post"
  -
    scope:
      path: "projects"
      type: "pages" # 以前的 `page`， 在 Jekyll 2.2 里。
    values:
      layout: "project" # 覆盖之前的默认布局
      author: "Mr. Hyde"

github_username: Snownight22

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

