name: 二十二夜的雪
permalink: :year/:month/:day/:title
baseurl: /cassidyblog
imgurl: /cassidyblog

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2022
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : tiantao5@gmail.com
  github : Snownight22
  weibo : https://weibo.com/u/1516249411
  weixin : https://mp.weixin.qq.com/s/zOmCbSw5DADT3-7l5yEt2Q
  link : https://snownight22.github.io/TTworksBlog/

# Links in the navigation, you can modify both link name and link url
nav:
    - title: "首页"
      english: "Home"
      path: "/"
      icon: "fa-home"
    - title: "归档"
      english: "Archive"
      path: "/archive"
      icon: "fa-archive"
    - title: "分类"
      english: "Categories"
      path: "/category"
      icon: "fa-tags"
    - title: "关于"
      english: "About"
      path: "/about"
      icon: "fa-info-circle"
    - title: "站内搜索"
      english: "Search"
      path: "/search"
      icon: "fa-search"
   
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed

gitalk:
  enable: true
  clientID: afddab7de04debfd2344
  clientSecret: daa6c46733b7e6a72d2eec30ec5c7bf61c279bdf


# leanCloud 配置
leanCloud:
  enable: true
  appId: vtrlGWXgg2lOLvgkgiLacWTE-gzGzoHsz
  appKey: QXTrNSAjMzhhYlGW1i1I3qWe
  counter: counter
